# How fast does an enemy accelerate downward while in the falling state?
fall_accel = 4.5

start_hp = 100.0

range_melee_melee = 12.0
range_melee_aggro = 100.0
range_melee_deaggro = 70.0
range_ranged_melee = 29.0
range_ranged_aggro = 100.0
range_ranged_ranged = 100.0
range_nearby = 20.0

walking_min_time = 24.0
walking_max_time = 300.0
idle_time = 240.0

projectile_arc_x = 134.0
projectile_arc_y = 151.0
projectile_damage = 20.0

melee_damage = 20.0

walking_speed = 20.0
chasing_speed = 35.0

fall_y_velocity = 30.0
jump_y_velocity = 140.0
