# Note: Setting some of these to negative values *WILL* cause a panic

# The maximum horizontal velocity the player can move at.
# (in pixels/second)
max_move_vel = 70.0

# The maximum downward velocity the player can fall at.
# (in pixels/second)
max_fall_vel = 180.0

# The initial acceleration applied to the player for the first tick they start moving.
# (in pixels/second^2)
move_accel_init = 20.0

# The acceleration applied to the player while they continue moving horizontally.
# (in pixels/second^2)
move_accel = 20.0

# How much velocity does the player have at the moment they jump?
# (in pixels/second)
jump_vel_init = 155.0

# How fast does the player accelerate downward while holding down the jump button?
# (in pixels/tick^2)
jump_fall_accel = 3.5

# How fast does the player accelerate downward while in the falling state?
# (ie: after releasing the jump key)
# (in pixels/tick^2)
# Note: sets the games global_gravity! (affects projectiles and other things that fall)
fall_accel = 4.5

# How many seconds does our characters innate hover boots work?
max_coyote_time = 0.1

# Only applies in the downward y direction while the player is falling
# and trying to walk into the wall
sliding_friction = 0.25

# How many ticks is the players velocity locked to zero after landing an attack?
hitfreeze_ticks = 45.0

# How many seconds does our character dash for?
dash_duration = 0.06

# How many seconds does our character dash down for?
dash_down_duration = 0.3

# How many seconds does our character stealth for?
stealth_duration = 3.0

# How many seconds does our character stealth for?
stealth_cooldown = 5.0

# How many pixels/s do they dash with?
dash_velocity = 400.0

# How many pixels/s do they dash down with, horizontally?
dash_down_horizontal_velocity = 500.0

# How many pixels/s do they dash down with, vertically?
dash_down_vertical_velocity = 500.0

# How long before the player can dash again?
dash_cooldown_duration = 1.0

# How long before the player can dash again?
dash_down_cooldown_duration = 5.0

max_whirl_energy = 5.0

# Spends this much energy per second when using whirl
whirl_cost = 2.0

# Spends this much energy per second when not using whirl
whirl_regen = 0.7

# How much max health the player has
max_health = 150.0

# Pushback velocity on wall jumps
wall_pushback = 50.0

# Ticks for wall pushback velocity; determines how long movement is locked for
wall_pushback_ticks = 5.0

# Pushback velocity on basic melee hits
melee_self_pushback = 60.0

# Ticks for melee pushback velocity; determines how long movement is locked for
melee_self_pushback_ticks = 3.0

# Knockback velocity applied to enemy on basic melee hit
melee_pushback = 60.0

# Ticks for melee knockback velocity; determines how long movement is locked for
melee_pushback_ticks = 12.0

# Base bow attack damage
bow_attack_damage = 15.0

# Pushback velocity on basic bow shots
bow_self_pushback = 0.0

# Ticks for bow pushback velocity; determines how long movement is locked for
bow_self_pushback_ticks = 0.0

# Knockback velocity applied to enemy on basic bow hit
bow_pushback = 60.0

# Ticks for melee knockback velocity; determines how long movement is locked for
bow_pushback_ticks = 5.0

# Number of kills to trigger passive gain
passive_gain_rate = 3.0

# Velocity of the projectiles fired by the Bow weapon
arrow_velocity = 1000.0
