atlas_asset_key = "anim.smallspider3.Decay.sprite"

[settings]
time_base = "Relative"
tick_quant = "8"
ticks_per_frame = 3_800_000
frame_min = 1
frame_max = 4
frame_start = 1

# Support left/right flipping
[[script]]
run_on_slot_enable = "DirectionLeft"
action = "SetSpriteFlip"
flip_x = true
[[script]]
run_on_slot_enable = "DirectionRight"
action = "SetSpriteFlip"
flip_x = false

# Decay rate control
[[script]]
run_on_slot_disable = "DecayRate"
action = "SetTicksPerFrame"
ticks_per_frame = 3_800_000
reset_progress = true


[[script]]
run_on_slot_enable = "DecayRate"
action = "SetTicksPerFrame"
ticks_per_frame = 3_800

[[script]]
run_at_frame = 4
action = "DespawnEntity"